services:
  online-exam:
    build:
      context: ./
      dockerfile: Dockerfile
    image: online-exam
    container_name: online-exam
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - /home/webserver/systems/Online-Exam-Test/.env:/var/www/.env
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./database:/var/www/database
    networks:
      - online-exam
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: online_exam
      DB_USERNAME: smct
      DB_PASSWORD: smct
      REDIS_HOST: 172.17.0.1
      REDIS_PORT: 6379

  online-exam-nginx:
    image: nginx:alpine
    container_name: online-exam-nginx
    restart: unless-stopped
    ports:
      - 7050:7050
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - online-exam

networks:
  online-exam:
    driver: bridge
